development:
  adapter: postgresql
  database: store_testing
  host: localhost 
  username: postgres
  password: media3
  poll: 10

test:
  adapter: postgresql
  database: store_testing
  host: localhost 
  username: postgres
  password: media3
  poll: 10

production:
  adapter: postgresql
  database: store_testing
  host: localhost 
  username: postgres
  password: media3
  poll: 10

  